#!/bin/sh

set -e
OWN_DIR="$(cd "$(dirname "$0")"; pwd)"
PROJECT_ROOT="$(cd "${OWN_DIR}/.."; pwd)"
DOCKER="${DOCKER:-"$(command -v docker)"}" || true
DOCKER="${DOCKER:-"docker"}"
HOST_IP="${HOST_IP:-"$("${DOCKER}" network inspect bridge -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}')"}"
PROJECT_PROXY_HOST="${PROJECT_PROXY_HOST:-"${HOST_IP}"}"
PROJECT_PROXY_PORT="${PROJECT_PROXY_PORT:-"${PROXY_PORT:-"3128"}"}"
PROJECT_NAME="${PROJECT_NAME:-"$(basename "${PROJECT_ROOT}")"}"
USER="${USER:-"$(id -un)"}"
USER_UID="${USER_UID:-"$(id -u)"}"
USER_GID="${USER_GID:-"$(id -g)"}"

JLINK_GNAME="${JLINK_GNAME:-"jlink"}"
JLINK_GID="${JLINK_GID:-"$(getent group "${JLINK_GNAME}" | cut -d: -f3)"}"

PLUGDEV_GNAME="${PLUGDEV_GNAME:-"plugdev"}"
PLUGDEV_GID="${PLUGDEV_GID:-"$(getent group "${PLUGDEV_GNAME}" | cut -d: -f3)"}"

cat >"${OWN_DIR}/devcontainer.env" <<ENVSUBST_EOF
# AUTOGENERATED AT $(date -Ins -u)
PROJECT_NAME="${PROJECT_NAME}"
PROJECT_PROXY_HOST="${PROJECT_PROXY_HOST}"
PROJECT_PROXY_PORT="${PROJECT_PROXY_PORT}"
HOST_IP="${HOST_IP}"
DISPLAY="${HOST_IP}${DISPLAY:-":1"}"
USER="${USER}"
USERNAME="${USER}"
USER_UID="${USER_UID}"
USER_GID="${USER_GID}"
TTY_GID="$(getent group tty | cut -d: -f3)"
DIALOUT_GID="$(getent group dialout | cut -d: -f3)"
INPUT_GID="$(getent group input | cut -d: -f3)"
USERS_GID="$(getent group users | cut -d: -f3)"
JLINK_GID="${JLINK_GID}"
JLINK_GNAME="${JLINK_GNAME}"
PLUGDEV_GID="${PLUGDEV_GID}"
PLUGDEV_GNAME="${PLUGDEV_GNAME}"
ENVSUBST_EOF
