#!/bin/sh

set -e
TARGET_FILENAME="$(basename "$0" .sh)"
ENV_FILENAME="devcontainer.env"
OWN_DIR="$(cd "$(dirname "$0")"; pwd)"
[ ! -e "${OWN_DIR}/${ENV_FILENAME}" ] && "${OWN_DIR}/${ENV_FILENAME}.sh"
. "${OWN_DIR}/${ENV_FILENAME}"
cat >"${OWN_DIR}/${TARGET_FILENAME}" <<ENVSUBST_EOF
# AUTOGENERATED AT $(date -Ins -u)
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
$(cat "${OWN_DIR}/${ENV_FILENAME}" | sed -E -e 's/^([^=]+)=/\1: /g' -e 's/^\s*#.*$//g' -e 's/^/        /g' | grep -vE '^\s*$')
    volumes:
      - source: ..
        target: /workspace
        type: bind
        consistency: consistent
      - source: /dev
        target: /dev
        type: bind
        consistency: consistent
      - source: /tmp/.X11-unix
        target: /tmp/.X11-unix
        type: bind
        consistency: consistent
    env_file:
      - ./devcontainer.env
    security_opt:
      - label=disable
    privileged: true
    command: sleep infinity
    # network_mode: service:proxy
    # depends_on:
    #   proxy:
    #     required: true
    #     condition: service_healthy
ENVSUBST_EOF
